export const colors = {
    primary: {
      50: "var(--amazigh-color-primary-50)",
      100: "var(--amazigh-color-primary-100)",
      200: "var(--amazigh-color-primary-200)",
      300: "var(--amazigh-color-primary-300)",
      400: "var(--amazigh-color-primary-400)",
      500: "var(--amazigh-color-primary-500)",
      600: "var(--amazigh-color-primary-600)",
      700: "var(--amazigh-color-primary-700)",
      800: "var(--amazigh-color-primary-800)",
      900: "var(--amazigh-color-primary-900)",
    },
    neutral: {
      50: "var(--amazigh-color-neutral-50)",
      100: "var(--amazigh-color-neutral-100)",
      200: "var(--amazigh-color-neutral-200)",
      300: "var(--amazigh-color-neutral-300)",
      400: "var(--amazigh-color-neutral-400)",
      500: "var(--amazigh-color-neutral-500)",
      600: "var(--amazigh-color-neutral-600)",
      700: "var(--amazigh-color-neutral-700)",
      800: "var(--amazigh-color-neutral-800)",
      900: "var(--amazigh-color-neutral-900)",
    },
    success: {
      50: "var(--amazigh-color-success-50)",
      500: "var(--amazigh-color-success-500)",
      900: "var(--amazigh-color-success-900)",
    },
    error: {
      50: "var(--amazigh-color-error-50)",
      500: "var(--amazigh-color-error-500)",
      900: "var(--amazigh-color-error-900)",
    },
  };
  
  export const space = {
    0: "0px",
    0.5: "var(--amazigh-space-0-5)",
    1: "var(--amazigh-space-1)",
    1.5: "var(--amazigh-space-1-5)",
    2: "var(--amazigh-space-2)",
    2.5: "var(--amazigh-space-2-5)",
    3: "var(--amazigh-space-3)",
    3.5: "var(--amazigh-space-3-5)",
    4: "var(--amazigh-space-4)",
    5: "var(--amazigh-space-5)",
    6: "var(--amazigh-space-6)",
    7: "var(--amazigh-space-7)",
    8: "var(--amazigh-space-8)",
    9: "var(--amazigh-space-9)",
    10: "var(--amazigh-space-10)",
    11: "var(--amazigh-space-11)",
    12: "var(--amazigh-space-12)",
    14: "var(--amazigh-space-14)",
    16: "var(--amazigh-space-16)",
    20: "var(--amazigh-space-20)",
    24: "var(--amazigh-space-24)",
    28: "var(--amazigh-space-28)",
    32: "var(--amazigh-space-32)",
    36: "var(--amazigh-space-36)",
    40: "var(--amazigh-space-40)",
    44: "var(--amazigh-space-44)",
    48: "var(--amazigh-space-48)",
    52: "var(--amazigh-space-52)",
    56: "var(--amazigh-space-56)",
    60: "var(--amazigh-space-60)",
    64: "var(--amazigh-space-64)",
    72: "var(--amazigh-space-72)",
    80: "var(--amazigh-space-80)",
    96: "var(--amazigh-space-96)",
  };
  
  export const fontSizes = {
    xs: "var(--amazigh-font-size-xs)",
    sm: "var(--amazigh-font-size-sm)",
    md: "var(--amazigh-font-size-md)",
    lg: "var(--amazigh-font-size-lg)",
    xl: "var(--amazigh-font-size-xl)",
    "2xl": "var(--amazigh-font-size-2xl)",
    "3xl": "var(--amazigh-font-size-3xl)",
    "4xl": "var(--amazigh-font-size-4xl)",
    "5xl": "var(--amazigh-font-size-5xl)",
    "6xl": "var(--amazigh-font-size-6xl)",
  };
  
  export const fontWeights = {
    hairline: "var(--amazigh-font-weight-hairline)",
    thin: "var(--amazigh-font-weight-thin)",
    light: "var(--amazigh-font-weight-light)",
    normal: "var(--amazigh-font-weight-normal)",
    medium: "var(--amazigh-font-weight-medium)",
    semibold: "var(--amazigh-font-weight-semibold)",
    bold: "var(--amazigh-font-weight-bold)",
    extrabold: "var(--amazigh-font-weight-extrabold)",
    black: "var(--amazigh-font-weight-black)",
  };
  
  export const lineHeights = {
    none: "var(--amazigh-line-height-none)",
    tight: "var(--amazigh-line-height-tight)",
    snug: "var(--amazigh-line-height-snug)",
    normal: "var(--amazigh-line-height-normal)",
    relaxed: "var(--amazigh-line-height-relaxed)",
    loose: "var(--amazigh-line-height-loose)",
  };
  
  export const radii = {
    none: "var(--amazigh-radius-none)",
    sm: "var(--amazigh-radius-sm)",
    md: "var(--amazigh-radius-md)",
    lg: "var(--amazigh-radius-lg)",
    xl: "var(--amazigh-radius-xl)",
    "2xl": "var(--amazigh-radius-2xl)",
    "3xl": "var(--amazigh-radius-3xl)",
    full: "var(--amazigh-radius-full)",
  };
  
  export const shadows = {
    sm: "var(--amazigh-shadow-sm)",
    md: "var(--amazigh-shadow-md)",
    lg: "var(--amazigh-shadow-lg)",
    xl: "var(--amazigh-shadow-xl)",
    "2xl": "var(--amazigh-shadow-2xl)",
    inner: "var(--amazigh-shadow-inner)",
    outline: "var(--amazigh-shadow-outline)",
    none: "var(--amazigh-shadow-none)",
  };
  
  export const zIndices = {
    hide: "var(--amazigh-z-index-hide)",
    auto: "var(--amazigh-z-index-auto)",
    base: "var(--amazigh-z-index-base)",
    docked: "var(--amazigh-z-index-docked)",
    dropdown: "var(--amazigh-z-index-dropdown)",
    sticky: "var(--amazigh-z-index-sticky)",
    banner: "var(--amazigh-z-index-banner)",
    overlay: "var(--amazigh-z-index-overlay)",
    modal: "var(--amazigh-z-index-modal)",
    popover: "var(--amazigh-z-index-popover)",
    toast: "var(--amazigh-z-index-toast)",
    tooltip: "var(--amazigh-z-index-tooltip)",
  };
