module.exports = {
    content: ["./src/**/*.{js,ts,jsx,tsx}"],
    darkMode: "class",
    theme: {
      extend: {
        colors: {
          primary: {
            50: "var(--amazigh-color-primary-50)",
            100: "var(--amazigh-color-primary-100)",
            200: "var(--amazigh-color-primary-200)",
            300: "var(--amazigh-color-primary-300)",
            400: "var(--amazigh-color-primary-400)",
            500: "var(--amazigh-color-primary-500)",
            600: "var(--amazigh-color-primary-600)",
            700: "var(--amazigh-color-primary-700)",
            800: "var(--amazigh-color-primary-800)",
            900: "var(--amazigh-color-primary-900)",
          },
          neutral: {
            50: "var(--amazigh-color-neutral-50)",
            100: "var(--amazigh-color-neutral-100)",
            200: "var(--amazigh-color-neutral-200)",
            300: "var(--amazigh-color-neutral-300)",
            400: "var(--amazigh-color-neutral-400)",
            500: "var(--amazigh-color-neutral-500)",
            600: "var(--amazigh-color-neutral-600)",
            700: "var(--amazigh-color-neutral-700)",
            800: "var(--amazigh-color-neutral-800)",
            900: "var(--amazigh-color-neutral-900)",
          },
          error: {
            50: "var(--amazigh-color-error-50)",
            500: "var(--amazigh-color-error-500)",
            900: "var(--amazigh-color-error-900)",
          },
          success: {
            50: "var(--amazigh-color-success-50)",
            500: "var(--amazigh-color-success-500)",
            900: "var(--amazigh-color-success-900)",
          },
          background: "var(--amazigh-background)",
          foreground: "var(--amazigh-text)",
          border: "var(--amazigh-border)",
        },
        borderRadius: {
          none: "var(--amazigh-radius-none)",
          sm: "var(--amazigh-radius-sm)",
          md: "var(--amazigh-radius-md)",
          lg: "var(--amazigh-radius-lg)",
          xl: "var(--amazigh-radius-xl)",
          "2xl": "var(--amazigh-radius-2xl)",
          "3xl": "var(--amazigh-radius-3xl)",
          full: "var(--amazigh-radius-full)",
        },
        boxShadow: {
          sm: "var(--amazigh-shadow-sm)",
          md: "var(--amazigh-shadow-md)",
          lg: "var(--amazigh-shadow-lg)",
          xl: "var(--amazigh-shadow-xl)",
          "2xl": "var(--amazigh-shadow-2xl)",
          inner: "var(--amazigh-shadow-inner)",
          outline: "var(--amazigh-shadow-outline)",
          none: "var(--amazigh-shadow-none)",
        },
        fontSize: {
          xs: "var(--amazigh-font-size-xs)",
          sm: "var(--amazigh-font-size-sm)",
          md: "var(--amazigh-font-size-md)",
          lg: "var(--amazigh-font-size-lg)",
          xl: "var(--amazigh-font-size-xl)",
          "2xl": "var(--amazigh-font-size-2xl)",
          "3xl": "var(--amazigh-font-size-3xl)",
          "4xl": "var(--amazigh-font-size-4xl)",
          "5xl": "var(--amazigh-font-size-5xl)",
          "6xl": "var(--amazigh-font-size-6xl)",
        },
        fontWeight: {
          hairline: "var(--amazigh-font-weight-hairline)",
          thin: "var(--amazigh-font-weight-thin)",
          light: "var(--amazigh-font-weight-light)",
          normal: "var(--amazigh-font-weight-normal)",
          medium: "var(--amazigh-font-weight-medium)",
          semibold: "var(--amazigh-font-weight-semibold)",
          bold: "var(--amazigh-font-weight-bold)",
          extrabold: "var(--amazigh-font-weight-extrabold)",
          black: "var(--amazigh-font-weight-black)",
        },
        lineHeight: {
          none: "var(--amazigh-line-height-none)",
          tight: "var(--amazigh-line-height-tight)",
          snug: "var(--amazigh-line-height-snug)",
          normal: "var(--amazigh-line-height-normal)",
          relaxed: "var(--amazigh-line-height-relaxed)",
          loose: "var(--amazigh-line-height-loose)",
        },
        zIndex: {
          hide: "var(--amazigh-z-index-hide)",
          auto: "var(--amazigh-z-index-auto)",
          base: "var(--amazigh-z-index-base)",
          docked: "var(--amazigh-z-index-docked)",
          dropdown: "var(--amazigh-z-index-dropdown)",
          sticky: "var(--amazigh-z-index-sticky)",
          banner: "var(--amazigh-z-index-banner)",
          overlay: "var(--amazigh-z-index-overlay)",
          modal: "var(--amazigh-z-index-modal)",
          popover: "var(--amazigh-z-index-popover)",
          toast: "var(--amazigh-z-index-toast)",
          tooltip: "var(--amazigh-z-index-tooltip)",
        },
      },
    },
    plugins: [],
  };
